services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    image: nginx:42
    ports:
     - "443:443"
    depends_on:
      - wordpress
    volumes:
     - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    image: wordpress:42
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always
networks:
  inception:
    name: inception
volumes:
        wordpress:
                name: wordpress
                driver: local
                driver_opts:
                        device: /home/jocorrea/inception-git/srcs/wordpress
                        o: bind
                        type: none