services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    image: nginx:42
    ports:
     - "443:443"
    networks:
      - inception
    env_file:
      - .env
    restart: always
networks:
  inception:
    name: inception
volumes:
        wordpress:
                name: wordpress
                driver: local
                driver_opts:
                        device: /home/jocorrea/inception-git/srcs/wordpress
                        o: bind
                        type: none