services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    image: nginx
    ports:
     - "443:443"
    depends_on:
      - wordpress
    volumes:
     - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    image: wordpress
    #depends_on:
     # - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always
#  mariadb:
#    container_name: mariadb
#    build: ./requirements/mariadb/.
#    image: mariadb:42
#    volumes:
#      - mariadb:/var/lib/mysql
#    env_file:
#      - .env
#    networks:
#      - inception
#    restart: always
networks:
  inception:
    name: inception
volumes:
        wordpress:
                name: wordpress
                driver: local
                driver_opts:
                        device: /home/jocorrea/inception-git/srcs/wordpress
                        o: bind
                        type: none
#        mariadb:
#                name: mariadb
#                driver: local
#                driver_opts:
#                        device: /home/jocorrea/inception/inception_git/srcs/mariadb
#                        o: bind
#                        type: none
